export { default as TestStats} from './TestStats/TestStats'
export { default as Chart } from './Chart/Chart'
export { default as Loading } from './Loading/Loading'
export { default as TestResults} from './TestResults/TestResults'
export { default as CommandLine} from './CommandLine/CommandLine'
export { default as Footer} from './Footer/Footer'
export { default as Header} from './Header/Header'
export { default as TypingTest} from './TypingTest/TypingTest'
