export { default as mean } from './mean'
export { default as StandardDeviation } from './standardDeviation'
export { default as coefficientOfVariation } from './coefficientOfVariation'
export { default as shuffleArray } from './shuffleArray'
export { default as kogasa } from './kogasa'
export { default as accuracy } from './accuracy'